language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
script:
- npm run lint
after_script:
- NODE_ENV=test ./node_modules/.bin/nyc npm test && ./node_modules/.bin/nyc report
  --reporter=text-lcov | coveralls
